version: "3.7"
services:
  base-php:
    build: php
    ports:
      - 8080:8080
    volumes:
      - ../:/var/www/
#      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - base
    command: symfony serve --port=8080

networks:
  base: